export let cards = [
    { img: './static/ace booby.png' },
    { img: './static/booby 9.png' },
    { img: './static/booby 8.png' },
    { img: './static/booby 7.png' },
    { img: './static/booby 6.png' },
    { img: './static/booby 10.png' },
    { img: './static/jakc of booby.png' },
    { img: './static/queen booby.png' },
    { img: './static/king booby.png' },

    { img: './static/ace peak.png' },
    { img: './static/peak 8.png' },
    { img: './static/peak 9.png' },
    { img: './static/peak 7.png' },
    { img: './static/peak 6.png' },
    { img: './static/peak 10.png' },
    { img: './static/jack peak.png' },
    { img: './static/queen peak.png' },
    { img: './static/king peak.png' },

    { img: './static/ace of hearts.png' },
    { img: './static/worm 8.png' },
    { img: './static/worm 9.png' },
    { img: './static/worm 7.png' },
    { img: './static/worm 6.png' },
    { img: './static/worm 10.png' },
    { img: './static/jack of hearts.png' },
    { img: './static/queen of hearts.png' },
    { img: './static/king worm.png' },

    { img: './static/ace cross.png' },
    { img: './static/cross 8.png' },
    { img: './static/worm 9.png' },
    { img: './static/worm 7.png' },
    { img: './static/worm 6.png' },
    { img: './static/worm 10.png' },
    { img: './static/jakc cross.png' },
    { img: './static/queen cross.png' },
    { img: './static/king cross.png' },
]
