export let cards = [
    { img: 'dist/static/ace booby.png' },
    { img: 'dist/static/booby 8.png' },
    { img: 'dist/static/booby 9.png' },
    { img: 'dist/static/booby 7.png' },
    { img: 'dist/static/booby 6.png' },
    { img: 'dist/static/booby 10.png' },
    { img: 'dist/static/jakc of booby.png' },
    { img: 'dist/static/queen booby.png' },
    { img: 'dist/static/king booby.png' },

    { img: 'dist/static/ace peak.png' },
    { img: 'dist/static/peak 8.png' },
    { img: 'dist/static/peak 9.png' },
    { img: 'dist/static/peak 7.png' },
    { img: 'dist/static/peak 6.png' },
    { img: 'dist/static/peak 10.png' },
    { img: 'dist/static/jack peak.png' },
    { img: 'dist/static/queen peak.png' },
    { img: 'dist/static/king peak.png' },

    { img: 'dist/static/ace of hearts.png' },
    { img: 'dist/static/worm 8.png' },
    { img: 'dist/static/worm 9.png' },
    { img: 'dist/static/worm 7.png' },
    { img: 'dist/static/worm 6.png' },
    { img: 'dist/static/worm 10.png' },
    { img: 'dist/static/jack of hearts.png' },
    { img: 'dist/static/queen of hearts.png' },
    { img: 'dist/static/king worm.png' },

    { img: 'dist/static/ace cross.png' },
    { img: 'dist/static/cross 8.png' },
    { img: 'dist/static/worm 9.png' },
    { img: 'dist/static/worm 7.png' },
    { img: 'dist/static/worm 6.png' },
    { img: 'dist/static/worm 10.png' },
    { img: 'dist/static/jakc cross.png' },
    { img: 'dist/static/queen cross.png' },
    { img: 'dist/static/king cross.png' },
]
