export let cards = [
    'img/ace booby.png',
    'img/booby 8.png',
    'img/booby 9.png',
    'img/booby 7.png"',
    'img/booby 6.png',
    'img/booby 10.png',
    'img/jakc of booby.png',
    'img/queen booby.png',
    'img/king booby.png',

    'img/ace peak.png',
    'img/peak 8.png',
    'img/peak 9.png',
    'img/peak 7.png',
    'img/peak 6.png',
    'img/peak 10.png',
    'img/jack peak.png',
    'img/queen peak.png',
    'img/king peak.png',

    'img/ace of hearts.png',
    'img/worm 8.png',
    'img/worm 9.png',
    'img/worm 7.png',
    'img/worm 6.png',
    'img/worm 10.png',
    'img/jack of hearts.png',
    'img/queen of hearts.png',
    'img/king worm.png',

    'img/ace cross.png',
    'img/cross 8.png',
    'img/worm 9.png',
    'img/worm 7.png',
    'img/worm 6.png',
    'img/worm 10.png',
    'img/jakc cross.png',
    'img/queen cross.png',
    'img/king cross.png',
]
